---
# tasks file for restart-service

- name: Registering {{ ip_address }} for {{ requestor }}
  shell: cd /home/common/scripts/ && python3 /home/common/scripts/ipAddCare.py {{ ip_address }} {{ requestor }} {{ ip_type }}