---
# tasks file for logrotate-s3
- name: Setting Rate Limits
  shell: aws configure set default.s3.max_concurrent_requests 1 && aws configure set default.s3.max_bandwidth 20MB/s
- name: Rotating Script
  shell: ~/scripts/CopyLogs.sh > /tmp/logrotate.log